parameters:
  eye_on_hand: true
  freehand_robot_movement: false
  move_group: xarm6
  move_group_namespace: /
  namespace: /xarm_realsense_handeyecalibration_eye_on_hand/
  robot_base_frame: link_base
  robot_effector_frame: link_eef
  tracking_base_frame: camera_color_optical_frame
  tracking_marker_frame: camera_marker
transformation:
  qw: 0.6994125796425928
  qx: -0.010512046039280014
  qy: -0.016676042801431423
  qz: 0.7144462540473192
  x: 0.06657634384046082
  y: 0.03553965217343794
  z: 0.08518873609747064